/* BOREXINO Reconstruction program
 *
 * This file was generated by ./create_linkdef.sh script: 
 * do NOT edit this file.
 *
 * linkdef definition for db_barn.hh
 */
#ifndef _BX_BARN_LINKDEF_HH
#define _BX_BARN_LINKDEF_HH
#if defined(__ROOTCLING__) || defined(__CINT__)
#define _ROOT_CINT_
#endif

#ifdef _ROOT_CINT_

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class bx_barn+;
#pragma link C++ class std::map<int, db_channel*>+;
#pragma link C++ class std::pair<int, db_channel*>+;
#endif
#endif

