/* BOREXINO Reconstruction program
 *
 * This file was generated by ./create_linkdef.sh script: 
 * do NOT edit this file.
 *
 * linkdef definition for db_channel.hh
 */
#ifndef _DB_CALIB_LINKDEF_HH
#define _DB_CALIB_LINKDEF_HH
#if defined(__ROOTCLING__) || defined(__CINT__)
#define _ROOT_CINT_
#endif

#ifdef _ROOT_CINT_

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class db_calib+;
#if ROOT_VERSION_CODE < 327680
#pragma link C++ class vector<float>; 
#endif

#endif
#endif
