/* BOREXINO Reconstruction program
 *
 * This file was generated by ./create_linkdef.sh script: 
 * do NOT edit this file.
 *
 * linkdef definition for db_channel.hh
 */
#ifndef _DB_CHANNEL_LINKDEF_HH
#define _DB_CHANNEL_LINKDEF_HH

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class db_channel+;
#pragma link C++ class db_channel_laben+;
#pragma link C++ class db_channel_muon+;

#endif
#endif
