/* BOREXINO Reconstruction program
 *
 * This file was generated by ./create_linkdef.sh script: 
 * do NOT edit this file.
 *
 * linkdef definition for bx_sample.hh
 */
#ifndef _BX_SAMPLE_LINKDEF_HH
#define _BX_SAMPLE_LINKDEF_HH

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;


#pragma link C++ class bx_alphabeta;

#endif
#endif
