// Class: ReadMLPv8
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : misiaszek
Date           : Tue Jul  7 04:58:47 2015
Host           : Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/misiaszek/bx_psd
Training events: 62000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "N+5,5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
laben.clusters[0].mean_time   laben.clusters_0_.mean_time   laben.clusters[0].mean_time   laben.clusters[0].mean_time                                     'F'    [31.6555404663,174.232299805]
laben.rec_clusters[0].rms     laben.rec_clusters_0_.rms     laben.rec_clusters[0].rms     laben.rec_clusters[0].rms                                       'F'    [30.8802585602,178.685424805]
laben.rec_clusters[0].kurtosis laben.rec_clusters_0_.kurtosis laben.rec_clusters[0].kurtosis laben.rec_clusters[0].kurtosis                                    'F'    [0.589003562927,129.12059021]
laben.rec_clusters[0].tailtot_ab_mlp[0] laben.rec_clusters_0_.tailtot_ab_mlp_0_ laben.rec_clusters[0].tailtot_ab_mlp[0] laben.rec_clusters[0].tailtot_ab_mlp[0]                                             'F'    [0.657439470291,1]
laben.rec_clusters[0].tailtot_ab_mlp[1] laben.rec_clusters_0_.tailtot_ab_mlp_1_ laben.rec_clusters[0].tailtot_ab_mlp[1] laben.rec_clusters[0].tailtot_ab_mlp[1]                                             'F'    [0.465564727783,0.916666686535]
laben.rec_clusters[0].tailtot_ab_mlp[2] laben.rec_clusters_0_.tailtot_ab_mlp_2_ laben.rec_clusters[0].tailtot_ab_mlp[2] laben.rec_clusters[0].tailtot_ab_mlp[2]                                             'F'    [0.275382488966,0.651724159718]
laben.rec_clusters[0].tailtot_ab_mlp[3] laben.rec_clusters_0_.tailtot_ab_mlp_3_ laben.rec_clusters[0].tailtot_ab_mlp[3] laben.rec_clusters[0].tailtot_ab_mlp[3]                                             'F'    [0.150769233704,0.482758611441]
laben.rec_clusters[0].tailtot_ab_mlp[4] laben.rec_clusters_0_.tailtot_ab_mlp_4_ laben.rec_clusters[0].tailtot_ab_mlp[4] laben.rec_clusters[0].tailtot_ab_mlp[4]                                             'F'    [0.0461538471282,0.321839094162]
laben.rec_clusters[0].tailtot_ab_mlp[5] laben.rec_clusters_0_.tailtot_ab_mlp_5_ laben.rec_clusters[0].tailtot_ab_mlp[5] laben.rec_clusters[0].tailtot_ab_mlp[5]                                             'F'    [0.0129870129749,0.29022988677]
laben.rec_clusters[0].tailtot_ab_mlp[6] laben.rec_clusters_0_.tailtot_ab_mlp_6_ laben.rec_clusters[0].tailtot_ab_mlp[6] laben.rec_clusters[0].tailtot_ab_mlp[6]                                             'F'    [0.00279329600744,0.258620679379]
laben.rec_clusters[0].tailtot_ab_mlp[7] laben.rec_clusters_0_.tailtot_ab_mlp_7_ laben.rec_clusters[0].tailtot_ab_mlp[7] laben.rec_clusters[0].tailtot_ab_mlp[7]                                             'F'    [0,0.238505750895]
laben.rec_clusters[0].tailtot_ab_mlp[8] laben.rec_clusters_0_.tailtot_ab_mlp_8_ laben.rec_clusters[0].tailtot_ab_mlp[8] laben.rec_clusters[0].tailtot_ab_mlp[8]                                             'F'    [0,0.221264362335]
laben.rec_clusters[0].tailtot_ab_mlp[9] laben.rec_clusters_0_.tailtot_ab_mlp_9_ laben.rec_clusters[0].tailtot_ab_mlp[9] laben.rec_clusters[0].tailtot_ab_mlp[9]                                             'F'    [0,0.206896558404]
NSpec 2
m4s.laben__cluster__npe_noavg_corrected charge                                  charge                                  charge                                                                              'F'    [350.095092773,1741.94274902]
m4s.laben__recon__r           r                             r                             r                                                               'F'    [-99,-99]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPv8 : public IClassifierReader {

 public:

   // constructor
   ReadMLPv8( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPv8" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "laben.clusters[0].mean_time", "laben.rec_clusters[0].rms", "laben.rec_clusters[0].kurtosis", "laben.rec_clusters[0].tailtot_ab_mlp[0]", "laben.rec_clusters[0].tailtot_ab_mlp[1]", "laben.rec_clusters[0].tailtot_ab_mlp[2]", "laben.rec_clusters[0].tailtot_ab_mlp[3]", "laben.rec_clusters[0].tailtot_ab_mlp[4]", "laben.rec_clusters[0].tailtot_ab_mlp[5]", "laben.rec_clusters[0].tailtot_ab_mlp[6]", "laben.rec_clusters[0].tailtot_ab_mlp[7]", "laben.rec_clusters[0].tailtot_ab_mlp[8]", "laben.rec_clusters[0].tailtot_ab_mlp[9]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPv8() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[6][19];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][6];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLPv8::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 6; fWeights[2] = new double[6]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.289421578184365;
   fWeightMatrix0to1[1][0] = 1.98662466682091;
   fWeightMatrix0to1[2][0] = 0.856103472742173;
   fWeightMatrix0to1[3][0] = 1.63129283991262;
   fWeightMatrix0to1[4][0] = -2.36471236244671;
   fWeightMatrix0to1[5][0] = -1.60179464800358;
   fWeightMatrix0to1[6][0] = -1.56400471403715;
   fWeightMatrix0to1[7][0] = 1.99560776829365;
   fWeightMatrix0to1[8][0] = -1.41328126450389;
   fWeightMatrix0to1[9][0] = -1.27274835772726;
   fWeightMatrix0to1[10][0] = -1.60902927251588;
   fWeightMatrix0to1[11][0] = -0.745426371266594;
   fWeightMatrix0to1[12][0] = -1.31050850872274;
   fWeightMatrix0to1[13][0] = -0.431172984790242;
   fWeightMatrix0to1[14][0] = -0.597867915001865;
   fWeightMatrix0to1[15][0] = 0.863583572254212;
   fWeightMatrix0to1[16][0] = -0.376662689356465;
   fWeightMatrix0to1[17][0] = 1.73448915680923;
   fWeightMatrix0to1[0][1] = 0.193224334762814;
   fWeightMatrix0to1[1][1] = 1.38256443567854;
   fWeightMatrix0to1[2][1] = -0.353443912688475;
   fWeightMatrix0to1[3][1] = -0.740855646262524;
   fWeightMatrix0to1[4][1] = 0.945158955811191;
   fWeightMatrix0to1[5][1] = 0.26426049606635;
   fWeightMatrix0to1[6][1] = -0.802274407963515;
   fWeightMatrix0to1[7][1] = -0.228345242191506;
   fWeightMatrix0to1[8][1] = 1.51252557920375;
   fWeightMatrix0to1[9][1] = -0.696357922209219;
   fWeightMatrix0to1[10][1] = -1.87415517681723;
   fWeightMatrix0to1[11][1] = 0.279367806142262;
   fWeightMatrix0to1[12][1] = 0.620014010194931;
   fWeightMatrix0to1[13][1] = 1.66498835151706;
   fWeightMatrix0to1[14][1] = -0.512369189320625;
   fWeightMatrix0to1[15][1] = -0.135937119755399;
   fWeightMatrix0to1[16][1] = 0.110984801957302;
   fWeightMatrix0to1[17][1] = -0.273729640618829;
   fWeightMatrix0to1[0][2] = -1.49521598744313;
   fWeightMatrix0to1[1][2] = 1.76048021744471;
   fWeightMatrix0to1[2][2] = -1.29894246775313;
   fWeightMatrix0to1[3][2] = 1.00906877066971;
   fWeightMatrix0to1[4][2] = 1.55973780179541;
   fWeightMatrix0to1[5][2] = 1.02417184950816;
   fWeightMatrix0to1[6][2] = 1.99094708238519;
   fWeightMatrix0to1[7][2] = 1.21323902542371;
   fWeightMatrix0to1[8][2] = -0.747707445107377;
   fWeightMatrix0to1[9][2] = -1.18470363930586;
   fWeightMatrix0to1[10][2] = 0.796789812145871;
   fWeightMatrix0to1[11][2] = 0.220368222955671;
   fWeightMatrix0to1[12][2] = 1.55046807587236;
   fWeightMatrix0to1[13][2] = 1.38134403051276;
   fWeightMatrix0to1[14][2] = 1.73903538002414;
   fWeightMatrix0to1[15][2] = 1.39765181734538;
   fWeightMatrix0to1[16][2] = -1.64591599532336;
   fWeightMatrix0to1[17][2] = 1.32467881399832;
   fWeightMatrix0to1[0][3] = -1.84570103293489;
   fWeightMatrix0to1[1][3] = -0.908463320133631;
   fWeightMatrix0to1[2][3] = -1.33643619264329;
   fWeightMatrix0to1[3][3] = -1.61211276688127;
   fWeightMatrix0to1[4][3] = 1.65974239485552;
   fWeightMatrix0to1[5][3] = 0.759814396050037;
   fWeightMatrix0to1[6][3] = -1.21912628986493;
   fWeightMatrix0to1[7][3] = 0.37084877215786;
   fWeightMatrix0to1[8][3] = -0.315926912162773;
   fWeightMatrix0to1[9][3] = 1.10812879025648;
   fWeightMatrix0to1[10][3] = 1.80530039275748;
   fWeightMatrix0to1[11][3] = -0.157696992247468;
   fWeightMatrix0to1[12][3] = 0.125607208882427;
   fWeightMatrix0to1[13][3] = -1.20308576065513;
   fWeightMatrix0to1[14][3] = 0.658968586234722;
   fWeightMatrix0to1[15][3] = -0.856769293897104;
   fWeightMatrix0to1[16][3] = -0.831947613040012;
   fWeightMatrix0to1[17][3] = -1.44831368932618;
   fWeightMatrix0to1[0][4] = 0.729788387773871;
   fWeightMatrix0to1[1][4] = 1.13343713547193;
   fWeightMatrix0to1[2][4] = 1.29875257175481;
   fWeightMatrix0to1[3][4] = -0.309108303365146;
   fWeightMatrix0to1[4][4] = -1.76040482485502;
   fWeightMatrix0to1[5][4] = -1.77746239815021;
   fWeightMatrix0to1[6][4] = 1.0076134565975;
   fWeightMatrix0to1[7][4] = 0.495774600965113;
   fWeightMatrix0to1[8][4] = 1.95512467852614;
   fWeightMatrix0to1[9][4] = 0.829502977606433;
   fWeightMatrix0to1[10][4] = 0.97902257128392;
   fWeightMatrix0to1[11][4] = -0.778966618467375;
   fWeightMatrix0to1[12][4] = -0.841802779218708;
   fWeightMatrix0to1[13][4] = -0.229437725090448;
   fWeightMatrix0to1[14][4] = 1.18327751549255;
   fWeightMatrix0to1[15][4] = -1.00190102133667;
   fWeightMatrix0to1[16][4] = -1.6003076355216;
   fWeightMatrix0to1[17][4] = -1.7109861732085;
   fWeightMatrix0to1[0][5] = -0.194896456230399;
   fWeightMatrix0to1[1][5] = -0.124231716039797;
   fWeightMatrix0to1[2][5] = 1.61589186965934;
   fWeightMatrix0to1[3][5] = -1.62047947294775;
   fWeightMatrix0to1[4][5] = -0.92438274297694;
   fWeightMatrix0to1[5][5] = 1.59232337110383;
   fWeightMatrix0to1[6][5] = -1.10520171288577;
   fWeightMatrix0to1[7][5] = -1.52331474730486;
   fWeightMatrix0to1[8][5] = -1.47987084542083;
   fWeightMatrix0to1[9][5] = 0.0420526757053438;
   fWeightMatrix0to1[10][5] = -1.92491304033657;
   fWeightMatrix0to1[11][5] = -1.73451085171548;
   fWeightMatrix0to1[12][5] = 0.714070226924177;
   fWeightMatrix0to1[13][5] = 1.66697667872502;
   fWeightMatrix0to1[14][5] = -1.1106843412886;
   fWeightMatrix0to1[15][5] = 1.65428201029654;
   fWeightMatrix0to1[16][5] = -0.911955464673984;
   fWeightMatrix0to1[17][5] = -0.807306109329368;
   fWeightMatrix0to1[0][6] = -0.00255955425512594;
   fWeightMatrix0to1[1][6] = 0.335589131865849;
   fWeightMatrix0to1[2][6] = -1.80309486238816;
   fWeightMatrix0to1[3][6] = 0.203741525287118;
   fWeightMatrix0to1[4][6] = 0.206876577498464;
   fWeightMatrix0to1[5][6] = 0.497097214573301;
   fWeightMatrix0to1[6][6] = -1.59094883057557;
   fWeightMatrix0to1[7][6] = 1.82430437221189;
   fWeightMatrix0to1[8][6] = 0.357070858857781;
   fWeightMatrix0to1[9][6] = -0.931656614606374;
   fWeightMatrix0to1[10][6] = 0.807186635833332;
   fWeightMatrix0to1[11][6] = -1.06171985111969;
   fWeightMatrix0to1[12][6] = -1.61755887944089;
   fWeightMatrix0to1[13][6] = 0.151802186609929;
   fWeightMatrix0to1[14][6] = -0.379953784274948;
   fWeightMatrix0to1[15][6] = 1.81374165203293;
   fWeightMatrix0to1[16][6] = 0.772120504547501;
   fWeightMatrix0to1[17][6] = -0.0249165646890799;
   fWeightMatrix0to1[0][7] = -0.290805842622482;
   fWeightMatrix0to1[1][7] = 0.159785184707417;
   fWeightMatrix0to1[2][7] = -1.82895378523978;
   fWeightMatrix0to1[3][7] = 0.950539516064202;
   fWeightMatrix0to1[4][7] = -0.15478514223391;
   fWeightMatrix0to1[5][7] = -1.86571017813542;
   fWeightMatrix0to1[6][7] = 0.251123216479495;
   fWeightMatrix0to1[7][7] = -1.44185183628522;
   fWeightMatrix0to1[8][7] = 0.0597151587138918;
   fWeightMatrix0to1[9][7] = 0.939425521863689;
   fWeightMatrix0to1[10][7] = 1.79549806341136;
   fWeightMatrix0to1[11][7] = -2.05102552164158;
   fWeightMatrix0to1[12][7] = 0.292750681372161;
   fWeightMatrix0to1[13][7] = 1.56283067572715;
   fWeightMatrix0to1[14][7] = 1.58471470208231;
   fWeightMatrix0to1[15][7] = 0.289451946891117;
   fWeightMatrix0to1[16][7] = -1.44569896527382;
   fWeightMatrix0to1[17][7] = -0.206401769542418;
   fWeightMatrix0to1[0][8] = -1.39711893104737;
   fWeightMatrix0to1[1][8] = 1.56645010551609;
   fWeightMatrix0to1[2][8] = 1.18694034945737;
   fWeightMatrix0to1[3][8] = -0.615322873859745;
   fWeightMatrix0to1[4][8] = -0.764155273272641;
   fWeightMatrix0to1[5][8] = 0.0783918634882956;
   fWeightMatrix0to1[6][8] = -1.89466283292679;
   fWeightMatrix0to1[7][8] = 0.608554412799851;
   fWeightMatrix0to1[8][8] = 1.71037825262658;
   fWeightMatrix0to1[9][8] = -0.760700676148186;
   fWeightMatrix0to1[10][8] = -0.583193868878445;
   fWeightMatrix0to1[11][8] = -0.0318364157139229;
   fWeightMatrix0to1[12][8] = 0.948674160825297;
   fWeightMatrix0to1[13][8] = 0.574739497850715;
   fWeightMatrix0to1[14][8] = 0.911731995974089;
   fWeightMatrix0to1[15][8] = -1.2637201268399;
   fWeightMatrix0to1[16][8] = 1.54747557998877;
   fWeightMatrix0to1[17][8] = 0.763137820142905;
   fWeightMatrix0to1[0][9] = 0.533346900611195;
   fWeightMatrix0to1[1][9] = 0.589329090204334;
   fWeightMatrix0to1[2][9] = 0.943489569071966;
   fWeightMatrix0to1[3][9] = -0.716208768893623;
   fWeightMatrix0to1[4][9] = -0.832709726144046;
   fWeightMatrix0to1[5][9] = 1.02916230274837;
   fWeightMatrix0to1[6][9] = -1.4881461154382;
   fWeightMatrix0to1[7][9] = -0.57434107397801;
   fWeightMatrix0to1[8][9] = 1.5836073615536;
   fWeightMatrix0to1[9][9] = 0.887723778891556;
   fWeightMatrix0to1[10][9] = -0.260920461870796;
   fWeightMatrix0to1[11][9] = 1.25406597586027;
   fWeightMatrix0to1[12][9] = 1.8096969689719;
   fWeightMatrix0to1[13][9] = -1.94693474533463;
   fWeightMatrix0to1[14][9] = 0.699882505268723;
   fWeightMatrix0to1[15][9] = 0.264790252406357;
   fWeightMatrix0to1[16][9] = 0.502609116736627;
   fWeightMatrix0to1[17][9] = -1.69905830446492;
   fWeightMatrix0to1[0][10] = -1.50809077472544;
   fWeightMatrix0to1[1][10] = 1.14654363830301;
   fWeightMatrix0to1[2][10] = 1.72206549274759;
   fWeightMatrix0to1[3][10] = -1.88007212652459;
   fWeightMatrix0to1[4][10] = -0.298373768047191;
   fWeightMatrix0to1[5][10] = -0.574335995448651;
   fWeightMatrix0to1[6][10] = -0.160966665165982;
   fWeightMatrix0to1[7][10] = 1.76725632072259;
   fWeightMatrix0to1[8][10] = -0.367845781643636;
   fWeightMatrix0to1[9][10] = -0.484096648694631;
   fWeightMatrix0to1[10][10] = -1.02525799087443;
   fWeightMatrix0to1[11][10] = 0.827523222405273;
   fWeightMatrix0to1[12][10] = 1.56292805344461;
   fWeightMatrix0to1[13][10] = 1.07382195773848;
   fWeightMatrix0to1[14][10] = 0.355497597194666;
   fWeightMatrix0to1[15][10] = -0.516578540457872;
   fWeightMatrix0to1[16][10] = -1.97346246355314;
   fWeightMatrix0to1[17][10] = 1.09896959584687;
   fWeightMatrix0to1[0][11] = 0.494489853263803;
   fWeightMatrix0to1[1][11] = -1.38924465325881;
   fWeightMatrix0to1[2][11] = -0.79038798487784;
   fWeightMatrix0to1[3][11] = 0.182336261219418;
   fWeightMatrix0to1[4][11] = 0.334935637858084;
   fWeightMatrix0to1[5][11] = -1.82513251170041;
   fWeightMatrix0to1[6][11] = 1.39775341812953;
   fWeightMatrix0to1[7][11] = 0.836185275884576;
   fWeightMatrix0to1[8][11] = -0.571951696129227;
   fWeightMatrix0to1[9][11] = 0.153366652340577;
   fWeightMatrix0to1[10][11] = 1.66093549694934;
   fWeightMatrix0to1[11][11] = 1.00413639336036;
   fWeightMatrix0to1[12][11] = 0.442689836487561;
   fWeightMatrix0to1[13][11] = -0.161729465442134;
   fWeightMatrix0to1[14][11] = -1.90602285424721;
   fWeightMatrix0to1[15][11] = -0.66576960234707;
   fWeightMatrix0to1[16][11] = 1.70226343020953;
   fWeightMatrix0to1[17][11] = 1.33911091914169;
   fWeightMatrix0to1[0][12] = 0.785245751189774;
   fWeightMatrix0to1[1][12] = 0.204516631262358;
   fWeightMatrix0to1[2][12] = 1.87056974929503;
   fWeightMatrix0to1[3][12] = -1.85339137050503;
   fWeightMatrix0to1[4][12] = -0.707945530366599;
   fWeightMatrix0to1[5][12] = 0.202374293107558;
   fWeightMatrix0to1[6][12] = -1.14664738618014;
   fWeightMatrix0to1[7][12] = 0.970913601346378;
   fWeightMatrix0to1[8][12] = 1.72898308876942;
   fWeightMatrix0to1[9][12] = -0.687143080549559;
   fWeightMatrix0to1[10][12] = 0.815052545307269;
   fWeightMatrix0to1[11][12] = 0.064617585454517;
   fWeightMatrix0to1[12][12] = -1.78801043439778;
   fWeightMatrix0to1[13][12] = -1.13194351919853;
   fWeightMatrix0to1[14][12] = 1.02207832419715;
   fWeightMatrix0to1[15][12] = 0.250134055581486;
   fWeightMatrix0to1[16][12] = 0.966629326089442;
   fWeightMatrix0to1[17][12] = -1.1433958123034;
   fWeightMatrix0to1[0][13] = 1.76919701985888;
   fWeightMatrix0to1[1][13] = -1.80715864451904;
   fWeightMatrix0to1[2][13] = 0.974575598473601;
   fWeightMatrix0to1[3][13] = 0.270230378160344;
   fWeightMatrix0to1[4][13] = -1.89704931216616;
   fWeightMatrix0to1[5][13] = -1.51025043940694;
   fWeightMatrix0to1[6][13] = -1.77033649235346;
   fWeightMatrix0to1[7][13] = -0.41743737741444;
   fWeightMatrix0to1[8][13] = -1.89384762067373;
   fWeightMatrix0to1[9][13] = -1.9645287885002;
   fWeightMatrix0to1[10][13] = -1.91779598900045;
   fWeightMatrix0to1[11][13] = 0.126035135125815;
   fWeightMatrix0to1[12][13] = -1.16247727976552;
   fWeightMatrix0to1[13][13] = -1.50265808039746;
   fWeightMatrix0to1[14][13] = 1.22337168567791;
   fWeightMatrix0to1[15][13] = -1.17004099237782;
   fWeightMatrix0to1[16][13] = 0.122269107291901;
   fWeightMatrix0to1[17][13] = -1.10267712252318;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.210777993376507;
   fWeightMatrix1to2[1][0] = 1.9705639257525;
   fWeightMatrix1to2[2][0] = 1.50928540072627;
   fWeightMatrix1to2[3][0] = -0.71836461027036;
   fWeightMatrix1to2[4][0] = -1.8817671169496;
   fWeightMatrix1to2[0][1] = -1.06501138093835;
   fWeightMatrix1to2[1][1] = -0.98409523758539;
   fWeightMatrix1to2[2][1] = -1.77634568935692;
   fWeightMatrix1to2[3][1] = 0.173487829248639;
   fWeightMatrix1to2[4][1] = 0.545257997229499;
   fWeightMatrix1to2[0][2] = 1.8825233654745;
   fWeightMatrix1to2[1][2] = -0.374904827261824;
   fWeightMatrix1to2[2][2] = 0.360688290566354;
   fWeightMatrix1to2[3][2] = -0.686214157829168;
   fWeightMatrix1to2[4][2] = -1.67080008096722;
   fWeightMatrix1to2[0][3] = 1.24507772815044;
   fWeightMatrix1to2[1][3] = 1.22755522172512;
   fWeightMatrix1to2[2][3] = -0.469968571311934;
   fWeightMatrix1to2[3][3] = -0.914456105173689;
   fWeightMatrix1to2[4][3] = 0.618463640100976;
   fWeightMatrix1to2[0][4] = 1.22370129609765;
   fWeightMatrix1to2[1][4] = 0.43683635803198;
   fWeightMatrix1to2[2][4] = -2.13434042928758;
   fWeightMatrix1to2[3][4] = -0.272413231547606;
   fWeightMatrix1to2[4][4] = 1.58278156013265;
   fWeightMatrix1to2[0][5] = 1.0026685862768;
   fWeightMatrix1to2[1][5] = 0.98532266406457;
   fWeightMatrix1to2[2][5] = -1.02853495563105;
   fWeightMatrix1to2[3][5] = 0.331843805455234;
   fWeightMatrix1to2[4][5] = -0.24641469870084;
   fWeightMatrix1to2[0][6] = -1.45895348384871;
   fWeightMatrix1to2[1][6] = -0.564565877047633;
   fWeightMatrix1to2[2][6] = -2.54182202241596;
   fWeightMatrix1to2[3][6] = -1.38725831201206;
   fWeightMatrix1to2[4][6] = -1.25610256975796;
   fWeightMatrix1to2[0][7] = 1.74920694104576;
   fWeightMatrix1to2[1][7] = -1.92310569408026;
   fWeightMatrix1to2[2][7] = 1.52338717345671;
   fWeightMatrix1to2[3][7] = -1.73970072836507;
   fWeightMatrix1to2[4][7] = 1.39088083894673;
   fWeightMatrix1to2[0][8] = -1.09626433856866;
   fWeightMatrix1to2[1][8] = 0.368698276773045;
   fWeightMatrix1to2[2][8] = 0.709668086082586;
   fWeightMatrix1to2[3][8] = -2.02566088928278;
   fWeightMatrix1to2[4][8] = 0.501013584898785;
   fWeightMatrix1to2[0][9] = 0.618890685405706;
   fWeightMatrix1to2[1][9] = -1.92060961279253;
   fWeightMatrix1to2[2][9] = -1.29065862863731;
   fWeightMatrix1to2[3][9] = -1.64296079349293;
   fWeightMatrix1to2[4][9] = -0.753251969943102;
   fWeightMatrix1to2[0][10] = 1.86929583671062;
   fWeightMatrix1to2[1][10] = -0.652864864366438;
   fWeightMatrix1to2[2][10] = 0.0663910794141878;
   fWeightMatrix1to2[3][10] = -1.04772654302062;
   fWeightMatrix1to2[4][10] = -0.798654944315475;
   fWeightMatrix1to2[0][11] = -1.7054955808946;
   fWeightMatrix1to2[1][11] = -1.01081061589274;
   fWeightMatrix1to2[2][11] = -1.52363577778782;
   fWeightMatrix1to2[3][11] = 0.836507404639522;
   fWeightMatrix1to2[4][11] = -1.13427385713137;
   fWeightMatrix1to2[0][12] = -1.21770061266359;
   fWeightMatrix1to2[1][12] = 1.65503584947096;
   fWeightMatrix1to2[2][12] = 0.201780565353371;
   fWeightMatrix1to2[3][12] = -0.68472565710156;
   fWeightMatrix1to2[4][12] = 2.22865267264818;
   fWeightMatrix1to2[0][13] = -1.79753032102791;
   fWeightMatrix1to2[1][13] = 1.3028287111541;
   fWeightMatrix1to2[2][13] = 0.843410061365747;
   fWeightMatrix1to2[3][13] = -1.1666966425024;
   fWeightMatrix1to2[4][13] = -0.473667439822108;
   fWeightMatrix1to2[0][14] = -0.0249637321087001;
   fWeightMatrix1to2[1][14] = -1.20108769990273;
   fWeightMatrix1to2[2][14] = 0.441706494682163;
   fWeightMatrix1to2[3][14] = 1.86454387693438;
   fWeightMatrix1to2[4][14] = 1.23102809425939;
   fWeightMatrix1to2[0][15] = 1.57407187153483;
   fWeightMatrix1to2[1][15] = -1.45234346567574;
   fWeightMatrix1to2[2][15] = 0.930384136909506;
   fWeightMatrix1to2[3][15] = -1.90052194524258;
   fWeightMatrix1to2[4][15] = 0.786287959467568;
   fWeightMatrix1to2[0][16] = -1.71439288442914;
   fWeightMatrix1to2[1][16] = -1.79960494509423;
   fWeightMatrix1to2[2][16] = 0.193355496832199;
   fWeightMatrix1to2[3][16] = 1.17510653707594;
   fWeightMatrix1to2[4][16] = 0.314218095894314;
   fWeightMatrix1to2[0][17] = 1.05169911758674;
   fWeightMatrix1to2[1][17] = 0.179523467076995;
   fWeightMatrix1to2[2][17] = -0.305068636102925;
   fWeightMatrix1to2[3][17] = -0.89547697743393;
   fWeightMatrix1to2[4][17] = 0.448101139276662;
   fWeightMatrix1to2[0][18] = 1.95396627715388;
   fWeightMatrix1to2[1][18] = -1.46091349812594;
   fWeightMatrix1to2[2][18] = 0.461595608314234;
   fWeightMatrix1to2[3][18] = -1.24615601473304;
   fWeightMatrix1to2[4][18] = -0.879876416913421;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.000217125119941251;
   fWeightMatrix2to3[0][1] = 0.0377277494381301;
   fWeightMatrix2to3[0][2] = -0.500347951975994;
   fWeightMatrix2to3[0][3] = 0.977294583519657;
   fWeightMatrix2to3[0][4] = 1.31243547364861;
   fWeightMatrix2to3[0][5] = 0.797363830049885;
}

inline double ReadMLPv8::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLPv8::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPv8::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPv8::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLPv8::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPv8::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 31.6555404663;
   fMax_1[0][0] = 90.4601898193;
   fMin_1[1][0] = 55.3858451843;
   fMax_1[1][0] = 174.232299805;
   fMin_1[2][0] = 31.6555404663;
   fMax_1[2][0] = 174.232299805;
   fMin_1[0][1] = 30.8802585602;
   fMax_1[0][1] = 113.817848206;
   fMin_1[1][1] = 60.9228057861;
   fMax_1[1][1] = 178.685424805;
   fMin_1[2][1] = 30.8802585602;
   fMax_1[2][1] = 178.685424805;
   fMin_1[0][2] = 4.93038702011;
   fMax_1[0][2] = 129.12059021;
   fMin_1[1][2] = 0.589003562927;
   fMax_1[1][2] = 36.1223907471;
   fMin_1[2][2] = 0.589003562927;
   fMax_1[2][2] = 129.12059021;
   fMin_1[0][3] = 0.657439470291;
   fMax_1[0][3] = 0.990808844566;
   fMin_1[1][3] = 0.718644082546;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0.657439470291;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0.465564727783;
   fMax_1[0][4] = 0.871794879436;
   fMin_1[1][4] = 0.553691267967;
   fMax_1[1][4] = 0.916666686535;
   fMin_1[2][4] = 0.465564727783;
   fMax_1[2][4] = 0.916666686535;
   fMin_1[0][5] = 0.275382488966;
   fMax_1[0][5] = 0.542522013187;
   fMin_1[1][5] = 0.380622833967;
   fMax_1[1][5] = 0.651724159718;
   fMin_1[2][5] = 0.275382488966;
   fMax_1[2][5] = 0.651724159718;
   fMin_1[0][6] = 0.150769233704;
   fMax_1[0][6] = 0.319565206766;
   fMin_1[1][6] = 0.227891162038;
   fMax_1[1][6] = 0.482758611441;
   fMin_1[2][6] = 0.150769233704;
   fMax_1[2][6] = 0.482758611441;
   fMin_1[0][7] = 0.0461538471282;
   fMax_1[0][7] = 0.161290317774;
   fMin_1[1][7] = 0.0960854068398;
   fMax_1[1][7] = 0.321839094162;
   fMin_1[2][7] = 0.0461538471282;
   fMax_1[2][7] = 0.321839094162;
   fMin_1[0][8] = 0.0129870129749;
   fMax_1[0][8] = 0.0907877162099;
   fMin_1[1][8] = 0.0645161271095;
   fMax_1[1][8] = 0.29022988677;
   fMin_1[2][8] = 0.0129870129749;
   fMax_1[2][8] = 0.29022988677;
   fMin_1[0][9] = 0.00279329600744;
   fMax_1[0][9] = 0.0667556747794;
   fMin_1[1][9] = 0.0260586310178;
   fMax_1[1][9] = 0.258620679379;
   fMin_1[2][9] = 0.00279329600744;
   fMax_1[2][9] = 0.258620679379;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 0.0547396540642;
   fMin_1[1][10] = 0.0162866450846;
   fMax_1[1][10] = 0.238505750895;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 0.238505750895;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 0.0485175214708;
   fMin_1[1][11] = 0.0096463020891;
   fMax_1[1][11] = 0.221264362335;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 0.221264362335;
   fMin_1[0][12] = 0;
   fMax_1[0][12] = 0.0437828376889;
   fMin_1[1][12] = 0;
   fMax_1[1][12] = 0.206896558404;
   fMin_1[2][12] = 0;
   fMax_1[2][12] = 0.206896558404;
}

//_______________________________________________________________________
inline void ReadMLPv8::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 13;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPv8::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPv8::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PSD MLPv8 filter

double PSD_MLPv8(const double& m4s_laben__ab__tail_to_total_35,  const double& m4s_laben__ab__tail_to_total_70, const double& m4s_laben__ab__tail_to_total_105, 
                 const double& m4s_laben__ab__tail_to_total_140, const double& m4s_laben__ab__tail_to_total_175, const double& m4s_laben__ab__tail_to_total_210, 
                 const double& m4s_laben__ab__tail_to_total_245, const double& m4s_laben__ab__tail_to_total_280, const double& m4s_laben__ab__tail_to_total_315, 
                 const double& m4s_laben__ab__tail_to_total_350, const double& m4s_laben__ab__rms, const double& m4s_laben__ab__kurtosis,
		 const double& laben_clusters_mean_time) {

  //register variables used during training
  static std::vector<std::string> input_vars(0);
  std::vector<double> input_values(0);

  if(input_vars.size() < 1) {
    input_vars.push_back("laben.clusters[0].mean_time"    );
    input_vars.push_back("laben.rec_clusters[0].rms" );
    input_vars.push_back("laben.rec_clusters[0].kurtosis" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[0]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[1]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[2]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[3]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[4]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[5]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[6]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[7]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[8]" );
    input_vars.push_back("laben.rec_clusters[0].tailtot_ab_mlp[9]" );
  }

  //create static MLP reader object
  static ReadMLPv8 reader(input_vars); 

  input_values.push_back(laben_clusters_mean_time);
  input_values.push_back(m4s_laben__ab__rms );
  input_values.push_back(m4s_laben__ab__kurtosis );
  input_values.push_back(m4s_laben__ab__tail_to_total_35 );
  input_values.push_back(m4s_laben__ab__tail_to_total_70 );
  input_values.push_back(m4s_laben__ab__tail_to_total_105);
  input_values.push_back(m4s_laben__ab__tail_to_total_140);
  input_values.push_back(m4s_laben__ab__tail_to_total_175);
  input_values.push_back(m4s_laben__ab__tail_to_total_210);
  input_values.push_back(m4s_laben__ab__tail_to_total_245);
  input_values.push_back(m4s_laben__ab__tail_to_total_280);
  input_values.push_back(m4s_laben__ab__tail_to_total_315);
  input_values.push_back(m4s_laben__ab__tail_to_total_350);

  return reader.GetMvaValue( input_values );

}
