#!/bin/sh
# Author: Alessandro Razeto <Alessandro.Razeto@ge.infn.it>
# Create the linkdef for the ClassDef definitions in the current
# directory

rm -f *LinkDef.hh

for i in *.hh; do
  classes=`grep ClassDef $i | sed -e s/.*\(// -e s/,.*$//`
  if [ $classes ]; then   
    file=`echo $i | sed s/\\\./LinkDef./` 
    ifdef=`echo _$i |tr [:lower:] [:upper:] | sed s/\\\./_LINKDEF_/`
    classdef=""
    for j in $classes; do
      tmp="#pragma link C++ class $j;"
      classdef=`echo -e "$classdef\n$tmp"`
    done
    cat > $file << EOF
/* BOREXINO Reconstruction program
 *
 * This file was generated by $0 script: 
 * do NOT edit this file.
 *
 * linkdef definition for $i
 */
#ifndef $ifdef
#define $ifdef
#if defined(__ROOTCLING__) || defined(__CINT__)
#define _ROOT_CINT_
#endif

#ifdef _ROOT_INT_

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

$classdef

#endif
#endif
EOF
  fi
done

